import crypto from "crypto";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { PrismaClient } from "../src/generated/prisma/client";
import villagesData from "../src/data/armenia-villages.json";
import { getYouTubeThumbnail } from "../src/lib/youtube";

const databaseUrl = process.env.DATABASE_URL ?? "file:./prisma/dev.db";
const adapter = new PrismaBetterSqlite3({ url: databaseUrl.replace(/^file:/, "") });
const prisma = new PrismaClient({ adapter });

// Villages come from src/data/armenia-villages.json, generated by
// scripts/extract-villages.mjs out of the GeoNames "AM" (Armenia) country
// dump, filtered to points that fall inside our 10 marz polygons
// (src/data/armenia-regions.geojson, from geoBoundaries). That spatial filter
// is what keeps this list to settlements within Armenia's own recognized
// territory only — nothing outside those 10 marz shapes is included.

const regions = [
  { slug: "aragatsotn", nameHy: "Արագածոտն", nameRu: "Арагацотн", nameEn: "Aragatsotn", lat: 40.3, lng: 44.35 },
  { slug: "ararat", nameHy: "Արարատ", nameRu: "Арарат", nameEn: "Ararat", lat: 39.95, lng: 44.75 },
  { slug: "armavir", nameHy: "Արմավիր", nameRu: "Армавир", nameEn: "Armavir", lat: 40.15, lng: 44.05 },
  { slug: "gegharkunik", nameHy: "Գեղարքունիք", nameRu: "Гегаркуник", nameEn: "Gegharkunik", lat: 40.35, lng: 45.35 },
  { slug: "kotayk", nameHy: "Կոտայք", nameRu: "Котайк", nameEn: "Kotayk", lat: 40.45, lng: 44.65 },
  { slug: "lori", nameHy: "Լոռի", nameRu: "Лори", nameEn: "Lori", lat: 41.05, lng: 44.6 },
  { slug: "shirak", nameHy: "Շիրակ", nameRu: "Ширак", nameEn: "Shirak", lat: 40.8, lng: 43.85 },
  { slug: "syunik", nameHy: "Սյունիք", nameRu: "Сюник", nameEn: "Syunik", lat: 39.35, lng: 46.35 },
  { slug: "tavush", nameHy: "Տավուշ", nameRu: "Тавуш", nameEn: "Tavush", lat: 40.9, lng: 45.2 },
  { slug: "vayots-dzor", nameHy: "Վայոց Ձոր", nameRu: "Вайоц Дзор", nameEn: "Vayots Dzor", lat: 39.75, lng: 45.35 },
] as const;

// Real lectures, sourced from the MTQARAN Academy YouTube playlist:
// https://www.youtube.com/playlist?list=PLY7A0f5wC8fhag7Wu7Srnhty4Is7v2Zf7
// Re-check that playlist for new uploads and add them here — this is meant
// to be the single source of truth for Academy lecture content going
// forward, not placeholder copy.
const lectureSeeds = [
  {
    slug: "mify-o-komitase",
    videoUrl: "https://www.youtube.com/watch?v=Q8TFgCrsmxc",
    titleHy: "«Միֆեր Կոմիտասի մասին» դասախոսություն",
    titleRu: "Лекция «Мифы о Комитасе»",
    titleEn: "Lecture: Myths about Komitas",
    descriptionHy: "Դասախոսություն Կոմիտաս Վարդապետի կերպարի շուրջ տարածված մի քանի պատմական առասպելների մասին։",
    descriptionRu: "Лекция о нескольких распространённых мифах вокруг личности Комитаса Вардапета — армянского священника, композитора и основоположника армянской этномузыкологии.",
    descriptionEn: "A lecture examining several widespread myths surrounding Komitas Vardapet, the Armenian priest, composer and founder of Armenian ethnomusicology.",
    category: "culture",
    durationMin: 34,
    featured: true,
  },
  {
    slug: "vani-tagavorutyan-chartarapetutyun",
    videoUrl: "https://www.youtube.com/watch?v=8alyHuGpgCg",
    titleHy: "«Վանի թագավորության ճարտարապետություն»",
    titleRu: "Архитектура Ванского царства",
    titleEn: "Architecture of the Kingdom of Van",
    descriptionHy: "Դասախոսություն Վանի թագավորության (Ուրարտու) ճարտարապետական ժառանգության մասին։",
    descriptionRu: "Лекция об архитектурном наследии Ванского царства (Урарту) — древнего государства в районе озера Ван.",
    descriptionEn: "A lecture on the architectural heritage of the Kingdom of Van (Urartu), the ancient state centered on Lake Van.",
    category: "history",
    durationMin: 21,
    featured: false,
  },
];

async function main() {
  console.log("Seeding regions...");
  const regionBySlug = new Map<string, string>();
  for (const r of regions) {
    const region = await prisma.region.upsert({
      where: { slug: r.slug },
      update: r,
      create: r,
    });
    regionBySlug.set(r.slug, region.id);
  }

  console.log(`Resetting villages/projects, importing ${villagesData.length} villages...`);
  await prisma.village.deleteMany(); // cascades to Project

  const villageRows = (
    villagesData as {
      slug: string;
      regionSlug: string;
      nameHy: string;
      nameRu: string;
      nameEn: string;
      lat: number;
      lng: number;
      population: number | null;
    }[]
  )
    .filter((v) => regionBySlug.has(v.regionSlug))
    .map((v) => ({
      id: crypto.randomUUID(),
      slug: v.slug,
      regionId: regionBySlug.get(v.regionSlug)!,
      nameHy: v.nameHy,
      nameRu: v.nameRu,
      nameEn: v.nameEn,
      lat: v.lat,
      lng: v.lng,
      population: v.population,
      workoutStatus: "proposed",
    }));

  await prisma.village.createMany({ data: villageRows });

  const workoutProjects = villageRows.map((v) => ({
    id: crypto.randomUUID(),
    villageId: v.id,
    type: "workout_ground",
    titleHy: `Մարզադաշտ՝ ${v.nameHy}`,
    titleRu: `Воркаут-площадка в с. ${v.nameRu}`,
    titleEn: `Workout ground in ${v.nameEn}`,
    descriptionHy: "Բացօթյա մարզադաշտի կառուցում գյուղի բնակիչների համար։",
    descriptionRu: "Строительство открытой воркаут-площадки для жителей деревни.",
    descriptionEn: "Building an outdoor workout ground for the village residents.",
    goalAmount: 4000000,
    raisedAmount: 0,
    status: "active",
  }));
  await prisma.project.createMany({ data: workoutProjects });

  // A couple of demo campaigns (one funded, one still fundraising) plus a
  // pending submission, so the moderation/progress-bar UI has something to
  // show without every one of the 1000+ villages looking identical.
  const demoVillage = villageRows.find((v) => v.slug === "voskevaz-aragatsotn");
  const secondDemoVillage = villageRows.find((v) => v.slug === "areni-vayots-dzor");
  if (demoVillage) {
    await prisma.project.updateMany({
      where: { villageId: demoVillage.id, type: "workout_ground" },
      data: { raisedAmount: 1250000, status: "active" },
    });
    await prisma.village.update({ where: { id: demoVillage.id }, data: { workoutStatus: "funding" } });

    await prisma.project.create({
      data: {
        villageId: demoVillage.id,
        type: "other",
        titleHy: "Գյուղական գրադարանի վերանորոգում",
        titleRu: "Ремонт сельской библиотеки",
        titleEn: "Village library renovation",
        descriptionHy: "Տանիքի և ջեռուցման վերանորոգում։",
        descriptionRu: "Ремонт кровли и системы отопления.",
        descriptionEn: "Roof and heating system repair.",
        goalAmount: 2500000,
        raisedAmount: 400000,
        status: "active",
      },
    });

    await prisma.project.create({
      data: {
        villageId: demoVillage.id,
        type: "other",
        titleHy: "Խաղահրապարակի կառուցում",
        titleRu: "Строительство детской площадки",
        titleEn: "Playground construction",
        goalAmount: 1500000,
        raisedAmount: 0,
        status: "pending",
        submittedBy: "demo",
        contact: "demo@example.com",
      },
    });
  }
  if (secondDemoVillage) {
    await prisma.project.updateMany({
      where: { villageId: secondDemoVillage.id, type: "workout_ground" },
      data: { raisedAmount: 3100000, status: "active" },
    });
    await prisma.village.update({ where: { id: secondDemoVillage.id }, data: { workoutStatus: "funding" } });
  }

  console.log("Resetting Academy content...");
  await prisma.lecture.deleteMany();
  await prisma.lecturer.deleteMany();

  console.log("Seeding lectures from the MTQARAN Academy playlist...");
  for (const l of lectureSeeds) {
    const data = { ...l, coverImage: getYouTubeThumbnail(l.videoUrl) };
    await prisma.lecture.upsert({
      where: { slug: l.slug },
      update: data,
      create: data,
    });
  }

  console.log("Done.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
